AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  trainsforgooglehomelambda
  
  Sample SAM Template for trainsforgooglehomelambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  trainsforgooglehomelambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: trainsforgooglehomelambda/
      Handler: main
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /
            Method: any
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: trainsforgooglehomelambda
          AWSRegion: eu-west-2
          secretName: prod/trainsforgooglehomelambda/parameters
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find  out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api

  trainsforgooglehomelambdaAPI:
    Description: "API Gateway endpoint URL for Dev environment for MySecond Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/"
  trainsforgooglehomelambdaFunction:
    Description: "MySecond Lambda Function ARN"
    Value: !GetAtt trainsforgooglehomelambdaFunction.Arn
  trainsforgooglehomelambdaFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt trainsforgooglehomelambdaFunctionRole.Arn
